Fandango/urls.py
from django.urls import path

from Fandango.views import (
    AddPegoste, HomePage, PegosteView, Pegostes, UpdatePegoste, Pegosteadores, PegosteadorHome, RedirectSlugPegoste
)


"""
The order of the paths is no accidental.
* <username> in the end is a string, so before evaluating it, check if catalog of Pegosteadores is being call.
* If it is not the catalog of pegosteadores, then proceed to resolve other possibilities.
* Starting with <username>:
  * If no other path is provided, then it will return the "home" page of that user, which will be the last pegoste, 
    if there is any.
  * if "pegostes" comes next, then show all the pegostes created in that blog, if there is any.
  * if "pegoste" comes after <username>, then check:
    * If "add" then display the form to create a pegoste.
    * If it is an ID, then redirect to the slug of that ID.
    * if it is a slug:
        * If "update" comes after the slug, then show the update form.
        * Otherwise, just display the pegoste.  
"""


app_name = 'Fandango'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('pegosteadores/', Pegosteadores.as_view(), name='pegosteadores'),
    path('<username>/', PegosteadorHome.as_view(), name='pegosteador_home'),
    path('<username>/pegostes/', Pegostes.as_view(), name='pegostes_list'),
    path('<username>/pegoste/add', AddPegoste.as_view(), name='add_pegoste'),
    path('<username>/pegoste/<int:pk>/', RedirectSlugPegoste.as_view(), name='pegoste_pk'),
    path('<username>/pegoste/<slug:slug>/update', UpdatePegoste.as_view(), name='update_pegoste'),
    path('<username>/pegoste/<slug:slug>/', PegosteView.as_view(), name='pegoste'),
]

Merequetengue/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', TemplateView.as_view(template_name='Merequetengue/about.html'), name='about'),
    path('accounts/', include('accounts.urls')),
    path('', include('Fandango.urls')),
]

# When running development server (default), there is need to add MEDIA_URL explicitly.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fandango/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


def get_default_user() -> User:
    """
    This callback method gets the User instance of user "anonymous" to be used when the
    original author was deleted.

    Note: This method is a proxy to allow the serialization of Pegoste class when
    being migrated to the DB.

    :return: The "anonymous" user

    Show username of default user

    >>> default_user = get_default_user()
    >>> default_user.username
    'anonymous'

    """
    return User.objects.get(username='anonymous')


def get_image_path(instance, filename: str) -> str:
    """
    This callback method returns the path in which images will be stored in MEDIA_ROOT directory. Using
    a universally unique identifier (UUID) to create unique folders for a user and pegoste. New images
    will be added, but previous ones won't be deleted.

    Note: This method is a proxy to allow the serialization of Pegoste class when
    being migrated to the DB.

    :param instance An object instance of Pegoste from which the user is being obtained.
    :param filename The name of the file uploaded.

    :return: The path in MEDIA_ROOT in which the image will be saved.
    """

    return '{user}/{uuid}/{file}'.format(user=instance.author.username, uuid=str(uuid.uuid4()), file=filename)


class Pegoste(models.Model):
    """
    Model to implement posts object in the application. Every attribute is mandatory.

    * title: The title of the post
    * subtitle: The sub-title of the post
    * publish_date: The date/time in which the post the post  was created.
    * author: Creator of the post. It is an implementation of User model for authentication porpoises.
    * content: The text of the post
    * image: A image part of the post

    Create new post

    >>> new_pegoste = Pegoste(
    ...     title='My Title',
    ...     subtitle='A new post',
    ...     author=User.objects.get(username='anonymous'),
    ...     content='Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
    ... )
    >>> new_pegoste.save()

    Check if it exists if the post exists.

    >>> Pegoste.objects.filter(title='My Title').exists()
    True

    Update title and subtitle

    >>> new_pegoste.title = 'New Title'
    >>> new_pegoste.subtitle = 'New subtitle for new title'
    >>> new_pegoste.save()
    >>> new_pegoste
    <Pegoste: New Title

    Delete post.

    >>> _ = Pegoste.objects.get(pk=new_pegoste.pk).delete()  # Delete object, but Skip operation's result
    >>> Pegoste.objects.filter(title='My Title').exists()
    False
    """

    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100, blank=True)
    publish_date = models.DateTimeField(default=timezone.now, editable=False)
    author = models.ForeignKey(User, on_delete=models.SET(get_default_user), editable=False)
    content = models.TextField()
    image = models.ImageField(upload_to=get_image_path, blank=True)
    slug = models.SlugField(max_length=50, editable=False)

    def get_absolute_url(self):
        """
        This method will be used by CreatePegoste and UpdatePegoste to redirect to the newly or updated Pegoste.
        Referencing URL setup pegoste to create the URL.

        :return: Absolute URL to current object.
        """

        return reverse('Fandango:pegoste', kwargs={'username': self.author.username, 'slug': self.slug})

    def __str__(self):
        return f'{self.title}'

Fandango/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, RedirectView, UpdateView
from django.views.generic.base import TemplateView

from Fandango.models import Pegoste


class HomePage(TemplateView):
    """
    Use of generic view to render homepage.
    """
    template_name = 'Fandango/home.html'


class Pegosteadores(ListView):
    """
    Display existing Fandango blog sites using username.
    """
    model = User
    template_name = 'Fandango/pegosteadores.html'

    def get_queryset(self):
        return self.model.objects.filter(Q(is_active=True) and Q(groups__name='Pegosteadores'))


class Pegostes(ListView):
    """
    A list of pegostes belonging to a pegosteador indicated by <username> in '<username>/' or 'Fandango:pegostes_list'.
    This is to limit the pegostes to be listed, since it makes no sense to show ALL the existing pegostes.
    """

    model = Pegoste
    template_name = 'Fandango/pegostes.html'

    def get_queryset(self):
        """
        Override of ListView.get_queryset() to return a query set of
        pegostes authored by a pegosteador indicated by 'username'.

        :return: Queryset with pegostes related to a pegosteador ('username')
        """
        return self.model.objects.filter(author__username=self.kwargs['username'])


class PegosteView(DetailView):
    """
    This view is used when URL dispatcher receives /<username>/pegoste/<slug> or 'Fandango:pegoste'. It will get the
    pegostes authored by a pegosteador indicated by <username>, then produce the pegoste referenced by <slug>.
    """

    model = Pegoste
    template_name = 'Fandango/pegoste_view.html'
    slug_field = 'slug'

    def get_queryset(self):
        """
        Overrides DetailView.get_queryset() to check if the pegosteador exists.

        :return: The query set with the pegostes beloging to a pegosteador.
        """

        return self.model.objects.filter(author__username=self.kwargs['username'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recents'] = self.get_queryset().filter().order_by('-publish_date')[:5]

        return context


class PegosteadorHome(PegosteView):
    """
    Implements PegosteView to get the last pegoste published by the pegosteador as the homepage. Extending PegosteView
    gives us a query set that already checks if the pegosteador exists, but now it will get the last pegoste.
    """

    def get_object(self, **kwargs):
        """
        Overriding PegosteView.get_object() to get the last pegoste published.

        :param kwargs: Default arguments passed by the class.
        :return: The last published pegoste by a pegosteador.
        """

        query_set = self.get_queryset()

        # If the pegosteador exists, check if it has at least a pegoste. If true, then
        # return the last one, otherwise it will not return anything.
        if query_set.count() >= 1:
            last_pegoste = query_set.last()
        else:
            last_pegoste = None

        return last_pegoste


class RedirectSlugPegoste(RedirectView):
    """
    This redirect prevents the use of PK in the URL to access a single pegoste, instead a slug will be use, thus
    redirecting to '<username>/pegoste/<slug>' or 'Fandango:pegoste'.
    """
    def get_redirect_url(self, *args, **kwargs):
        pegoste = get_object_or_404(Pegoste, pk=kwargs['pk'])
        return pegoste.get_absolute_url()


class RedirectAuth(RedirectView):
    """
    Simple redirect used after registration of a new pegosteador. This has the porpoise of separating URLs
    dispatching from each application.
    """
    def get_redirect_url(self, *args, **kwargs):
        if 'username' in self.kwargs:
            redirect_to = reverse('Fandango:pegosteador_home')
        else:
            redirect_to = reverse('Fandango:home')
        return redirect_to


# ToDo: Implement AccessMixin to restrict the addition and update of pegostes to the pegosteador logged in.
class AddPegoste(LoginRequiredMixin, CreateView):
    """
    The mixin view LoginRequiredMixin implements authentication mechanisms, so there is no need to write additional
    functionality or validations. For this to work, the first class in the definition of the view must be
    LoginRequiredMixin and then the generic view class.

    The default behavior of the mixin is to redirect to the login URL. The default value of "login_url" attribute
    in LoginRequiredMixin is the value in settings.LOGIN_URL, that its default value is 'accounts/login'.
    In this case, LoginRequiredMixin will use defaults.

      Reference:
        https://docs.djangoproject.com/en/4.1/topics/auth/default/#the-loginrequiredmixin-mixin
        https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-LOGIN_URL
    """

    model = Pegoste
    fields = '__all__'
    template_name = 'Fandango/add_update_pegoste.html'


# ToDo: Implement AccessMixin to restrict the addition and update of pegostes to the pegosteador logged in.
class UpdatePegoste(LoginRequiredMixin, UpdateView):
    """
    The mixin view LoginRequiredMixin implements authentication mechanisms, so there is no need to write additional
    functionality or validations. For this to work, the first class in the definition of the view must be
    LoginRequiredMixin and then the generic view class.

    The default behavior of the mixin is to redirect to the login URL. The default value of "login_url" attribute
    in LoginRequiredMixin is the value in settings.LOGIN_URL, that its default value is 'accounts/login'.
    In this case, LoginRequiredMixin will use defaults.

      Reference:
        https://docs.djangoproject.com/en/4.1/topics/auth/default/#the-loginrequiredmixin-mixin
        https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-LOGIN_URL
    """

    model = Pegoste
    fields = '__all__'
    template_name = 'Fandango/add_update_pegoste.html'

templates/Fandango/add_update_pegoste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Pegoste</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

templates/Fandango/create_pegoste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Pegoste</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

templates/Fandango/home.html
{% extends 'Merequetengue/base_template.html' %}

templates/Fandango/pegoste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object.title }}</title>
</head>
<body>
<h1>{{ object.title }}</h1>
<h2>{{ object.subtitle }}</h2>

<p>
    {{ object.content }}
</p>

{% if object.image %}
<p>
    <img src="{{ object.image.url }}" alt="{{ object.image.name }}">
</p>
{% endif %}

<p>
    Pegosteado by <strong>{{ pegoste.author.first_name }} {{ pegoste.author.last_name }}</strong>
    on <em>{{ object.publish_date }}</em>
</p>

</body>
</html>

templates/Fandango/pegoste_view.html
{% extends 'Merequetengue/base_template.html' %}

{% block title %}
    {% if pegoste %}
        {{ pegoste.title }}
    {% else %}
        I do not think so...
    {% endif %}
{% endblock %}

{% block content %}
    {% if pegoste %}

        <h1>{{ pegoste.title }}</h1>

        {% if pegoste.subtitle %}
            <h2>{{ pegoste.subtitle }}</h2>
        {% endif %}
        <p>
            {{ pegoste.content }}
        </p>

        {% if pegoste.image %}
            <p>
                <img src="{{ pegoste.image.url }}" alt="{{ pegoste.image.name }}">
            </p>
        {% endif %}

        <p>
            Pegosteado by <strong>{{ pegoste.author.get_full_name }}</strong>
            on <em>{{ object.publish_date }}</em>
        </p>
    {% else %}
        <p>That pegoste does not exists!</p>
    {% endif %}
{% endblock %}

{% block recent %}
    {% if recents %}
        Still warm...
        <ul>
            {% for recent in recents %}
                <li><a href="{% url 'Fandango:pegoste' recent.author.username recent.slug %}">{{ recent.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        No recent pegostes
    {% endif %}
{% endblock %}

templates/Fandango/pegosteadores.html
{% extends 'Merequetengue/base_template.html' %}

{% block title %}Pegosteadores{% endblock %}

{% block content %}
    {% if user_list %}

        <h1>Already pegosteando</h1>
        <ul>
            {% for user in user_list %}
                <li>
                    <a href="{% url 'Fandango:pegosteador_home' user.username %}">{{ user.username }}</a> by {{ user.first_name }} {{ user.last_name }}
                </li>
            {% endfor %}
        </ul>

    {% else %}
        No pegosteadores yet? Dude, step up your game!
    {% endif %}
{% endblock %}

templates/Fandango/pegostes.html
{% extends 'Merequetengue/base_template.html' %}

{% block title %}[[ user.username }} | Pegostes{% endblock %}

{% block content %}
    {% if pegoste_list %}

        <ul>
        {% for pegoste in pegoste_list %}
        <li>
            <a href="{% url 'Fandango:pegoste' pegoste.author.username pegoste.slug %}">{{ pegoste.title }}</a>
        </li>
        {% endfor %}
        </ul>

    {% else %}
        No pegosteadores yet? Dude, step up your game!
    {% endif %}
{% endblock %}